image: ennovarplayerone/dockerindocker 
test:
  script:
  - usermod -aG docker ${USER}
  - docker-compose build 
  - docker-compose run api rake db:create
  - docker-compose run api rake db:migrate 
  - docker-compose run api rake
  - ls -a
  - 'curl -i -H "Content-Type: application/json" -X POST -d @.gitlabinfo http://10.16.20.22:8080/deploy'
  - echo 'success'

